services:
  scheduler:
    env_file:
      - schedulerservice/.env.local
      - schedulerservice/.env
      - ./.env.root
    environment:
      DOCKER: "true"
    build:
      context: schedulerservice
    ports:
      - "3304:3304"
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      app-network:
  worker:
    env_file:
      - schedulerservice/.env
      - ./.env.root
    build:
      context: schedulerservice
    restart: unless-stopped
    healthcheck:
      disable: true
    working_dir: /app
    command: sh -c "npm run build && npm run worker"
    depends_on:
      pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      app-network:
    volumes:
      - ./schedulerservice:/app           
      - /app/dist  

networks:
  app-network:
    driver: bridge