FROM node:24-alpine

RUN apk add --no-cache curl

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./

RUN npx prisma generate

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3302

CMD ["node", "dist/src/server.js"]

HEALTHCHECK --interval=5s --timeout=3s --retries=5 CMD sh -c "curl -f http://localhost:3304/health/live && curl -f http://localhost:3304/health/ready || exit 1"
